// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdL8MpKhXPbKkSb_azc-R-UHqYvZXyBrI',
    appId: '1:1032508482648:web:07967d393df5d7921b962d',
    messagingSenderId: '1032508482648',
    projectId: 'twista-384aa',
    authDomain: 'twista-384aa.firebaseapp.com',
    storageBucket: 'twista-384aa.appspot.com',
    measurementId: 'G-SK20ENM3G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-hBSlaaPU8bog8xIt-WAQmjJhZbYGx0',
    appId: '1:1032508482648:android:cb9a1fea6bd5cb221b962d',
    messagingSenderId: '1032508482648',
    projectId: 'twista-384aa',
    storageBucket: 'twista-384aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLWQBwW-MrAnVaOyaB_6DRCO6gh5W0INA',
    appId: '1:1032508482648:ios:d6660650143e4fa51b962d',
    messagingSenderId: '1032508482648',
    projectId: 'twista-384aa',
    storageBucket: 'twista-384aa.appspot.com',
    androidClientId: '1032508482648-2b6tuc1n3lja91v8udg6bter3ohqqrn4.apps.googleusercontent.com',
    iosClientId: '1032508482648-ntr6hf6eiie1783u9g6dhrc9hu4vk216.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.TwistaStore',
  );
}
